---
title: "DevelopingDataProducts_Week_2"
author: "Betty Matter"
date: "8/21/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(shiny)
library(leaflet)
library(htmltools)
library(dplyr)
```

## Get Data file from github

```{r echo=TRUE}
dc_schools<-read.csv("https://raw.githubusercontent.com/bettyak/Developing_Data_Products/main/DC_Schools.csv", header =TRUE)
```

## Modify data

```{r echo=TRUE}
dc_schools=rename(dc_schools, school=ï..school)
dc_schools[is.na(dc_schools)]=0
dc_schools$totalCases= rowSums(dc_schools[,c(5:22)])

```

## Cut variables into bins

```{r echo=TRUE}
dc_schools$totalCasesLvl <- cut(dc_schools$totalCases, 
                                c(1,3,7,17), include.lowest = T,
                                labels = c('<3', '3-7', '7+'))
```

## Assign Palette Using Color Factor

```{r echo=TRUE}
caseCol <- colorFactor(palette = 'Dark2', dc_schools$totalCasesLvl)

```

## define ui
```{r echo = TRUE}
ui<-fluidPage(
    leafletOutput("mymap"),
    )
```


##define server

```{r echo=TRUE}
server<-function(input, output) {
    
    
    output$mymap <- renderLeaflet({ 
        
        my_map<-leaflet(data=dc_schools) %>% 
        addTiles() %>% 
        addCircleMarkers(~Long,~Lat, 
                         radius = ~sqrt(totalCases*30), 
                         label = ~htmlEscape(school), 
                         popup = ~htmlEscape(totalCases), 
                         color=~caseCol(totalCasesLvl))%>%
        addLegend('bottomright', pal = caseCol, values =dc_schools$totalCasesLvl,
                  title = 'Douglas County Schools Covid Cases',
                  opacity = 1)
        return(my_map)
})
}

```

## Combine server and ui

```{r echo = TRUE}
shinyApp(ui = ui, server=server)
```
